
local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "esES", false)
if not L then return end





-- L["ALPHAPANEL_TITLE"] = ""
-- L["BleedDamageTaken"] = ""
-- L["Bleeding"] = ""
-- L["BonusAgiStr"] = ""
-- L["BonusArmor"] = ""
-- L["BonusMana"] = ""
-- L["BonusStamina"] = ""
-- L["BurstHaste"] = ""
-- L["BurstManaRegen"] = ""
-- L["CASTERFORM"] = ""
L["CHOOSENAME_DIALOG"] = [=[Introduzca el nombre o la identificación de los hechizos / Capacidad / artículo / Buff / Debuff desea que este icono de la pantalla. Usted puede agregar múltiples Buffs / Debuffs separándolas con';'.
HABILIDADES PET debe utilizar SpellIDs.]=] -- Needs review
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "Conjuntos predefinidos Hechizo" -- Needs review
L["CHOOSENAME_EQUIVS_TOOLTIP"] = "Usted puede seleccionar un conjunto predefinido de aficionados / desventajas de este menú." -- Needs review
L["CMD_ERROR"] = "No se puede cambiar de configuración TellMeWhen en combate" -- Needs review
L["CMD_OPTIONS"] = "Opciones" -- Needs review
L["CMD_RESET"] = "reset" -- Needs review
-- L["CONDITIONPANEL_ALIVE"] = ""
-- L["CONDITIONPANEL_ALIVE_DESC"] = ""
L["CONDITIONPANEL_AND"] = "Y"
L["CONDITIONPANEL_ANDOR"] = "Y / O"
-- L["CONDITIONPANEL_COMBO"] = ""
L["CONDITIONPANEL_ECLIPSE_DESC"] = [=[Eclipse tiene un rango de -100 (un eclipse lunar) a 100 (un eclipse solar) 
Percentages trabajo de la misma manera:. 
Input -80 si desea que el icono de trabajar con un valor de 80 energía lunar. ]=] -- Needs review
L["CONDITIONPANEL_EQUALS"] = "iguales" -- Needs review
-- L["CONDITIONPANEL_EXISTS"] = ""
-- L["CONDITIONPANEL_EXISTS_DESC"] = ""
L["CONDITIONPANEL_GREATER"] = "mayor que" -- Needs review
L["CONDITIONPANEL_GREATEREQUAL"] = "Mayor o igual a" -- Needs review
-- L["CONDITIONPANEL_ICON"] = ""
-- L["CONDITIONPANEL_ICON_DESC"] = ""
L["CONDITIONPANEL_LESS"] = "menor que" -- Needs review
L["CONDITIONPANEL_LESSEQUAL"] = "Menor o igual a" -- Needs review
L["CONDITIONPANEL_NOTEQUAL"] = "No es igual a" -- Needs review
L["CONDITIONPANEL_OPERATOR"] = "operador" -- Needs review
L["CONDITIONPANEL_OR"] = "O"
-- L["CONDITIONPANEL_POWER"] = ""
L["CONDITIONPANEL_POWER_DESC"] = [=[buscará la energía si la unidad es un druida en forma de gato, 
rage si la unidad es un guerrero, etc]=] -- Needs review
L["CONDITIONPANEL_RESET"] = "Borrar" -- Needs review
L["CONDITIONPANEL_TITLE"] = "TellMeWhen Editor de Estado" -- Needs review
L["CONDITIONPANEL_TYPE"] = "Tipo" -- Needs review
L["CONDITIONPANEL_UNIT"] = "Unidad"
L["CONDITIONPANEL_VALUE"] = "Porcentaje" -- Needs review
-- L["CONDITIONPANEL_VALUEN"] = ""
-- L["CONDTWARN"] = ""
-- L["COPY"] = ""
-- L["COPYPANEL_GROUP"] = ""
-- L["COPYPANEL_ICON"] = ""
-- L["COPYPANEL_TITLE"] = ""
-- L["COPYSETTINGS"] = ""
-- L["CrowdControl"] = ""
-- L["Curse"] = ""
-- L["DURATIONPANEL_TITLE"] = ""
-- L["Disarmed"] = ""
-- L["Disease"] = ""
-- L["Disoriented"] = ""
-- L["ECLIPSE_DIRECTION"] = ""
-- L["ECLIPSE_DIRECTION_DESC"] = ""
-- L["EDITORPANEL_TITLE"] = ""
-- L["FALSE"] = ""
-- L["FROM"] = ""
-- L["Feared"] = ""
-- L["GENABLEBUTTON"] = ""
-- L["GROUP"] = ""
-- L["GROUPICON"] = ""
-- L["GROUPRESETMSG"] = ""
-- L["HPSSWARN"] = ""
L["ICONALPHAPANEL_ALPHA"] = "utilizable / Nivel Alfa actual" -- Needs review
L["ICONALPHAPANEL_ALPHA_DESC"] = "Slide para establecer el nivel alfa para el icono cuando la habilidad se puede usar / presente" -- Needs review
-- L["ICONALPHAPANEL_CNDTALPHA"] = ""
-- L["ICONALPHAPANEL_CNDTALPHA_DESC"] = ""
-- L["ICONALPHAPANEL_DURATIONALPHA"] = ""
-- L["ICONALPHAPANEL_DURATIONALPHA_DESC"] = ""
-- L["ICONALPHAPANEL_FAKEHIDDEN"] = ""
-- L["ICONALPHAPANEL_FAKEHIDDEN_DESC"] = ""
-- L["ICONALPHAPANEL_STACKALPHA"] = ""
-- L["ICONALPHAPANEL_STACKALPHA_DESC"] = ""
-- L["ICONALPHAPANEL_THISISSET_DESC"] = ""
L["ICONALPHAPANEL_UNALPHA"] = "inutilizable / Nivel Alfa ausente" -- Needs review
L["ICONALPHAPANEL_UNALPHA_DESC"] = "Slide para establecer el nivel alfa para el icono cuando la capacidad no se puede usar / ausente" -- Needs review
L["ICONMENU_ABSENT"] = "Ausente"
L["ICONMENU_ADDCONDITION"] = "Añadir condición" -- Needs review
L["ICONMENU_ALPHA"] = "Alfa" -- Needs review
L["ICONMENU_ALWAYS"] = "Siempre"
L["ICONMENU_BARS"] = "pubs" -- Needs review
-- L["ICONMENU_BOTH"] = ""
L["ICONMENU_BUFF"] = "Buff"
L["ICONMENU_BUFFDEBUFF"] = "Buff / Debuff" -- Needs review
L["ICONMENU_BUFFSHOWWHEN"] = "Mostrar al aficionado / desventaja" -- Needs review
L["ICONMENU_BUFFTYPE"] = "Buff o desventaja?" -- Needs review
-- L["ICONMENU_CAST"] = ""
-- L["ICONMENU_CASTSHOWWHEN"] = ""
-- L["ICONMENU_CAST_DESC"] = ""
L["ICONMENU_CHOOSENAME"] = "Elige hechizo / artículo / beige / etc." -- Needs review
L["ICONMENU_CLEAR"] = "Borrar los valores" -- Needs review
L["ICONMENU_COOLDOWN"] = "Tiempo de reutilización" -- Needs review
-- L["ICONMENU_COOLDOWNCHECK"] = ""
-- L["ICONMENU_COOLDOWNCHECK_DESC"] = ""
L["ICONMENU_COOLDOWNTYPE"] = "tipo de tiempo de reutilización" -- Needs review
L["ICONMENU_DEBUFF"] = "Desventaja" -- Needs review
-- L["ICONMENU_DISPEL"] = ""
L["ICONMENU_DURATIONANDCD"] = "--unused"
-- L["ICONMENU_DURATION_MAX_DESC"] = ""
-- L["ICONMENU_DURATION_MIN_DESC"] = ""
-- L["ICONMENU_EDIT"] = ""
L["ICONMENU_EDITCONDITION"] = "Editar condición" -- Needs review
L["ICONMENU_EITHER"] = "Todas las unidades" -- Needs review
L["ICONMENU_ENABLE"] = "Habilitar el icono" -- Needs review
L["ICONMENU_FOCUSTARGET"] = "Focus' target" -- Needs review
L["ICONMENU_FRIEND"] = "Unidades Amigas"
-- L["ICONMENU_HIDEUNEQUIPPED"] = ""
L["ICONMENU_HOSTILE"] = "Unidades Hostiles"
-- L["ICONMENU_ICONS"] = ""
L["ICONMENU_INVERTBARS"] = "Llene barras de arriba" -- Needs review
L["ICONMENU_ITEM"] = "elemento" -- Needs review
L["ICONMENU_MANACHECK"] = "Comprobar poder?" -- Needs review
-- L["ICONMENU_MANACHECK_DESC"] = ""
-- L["ICONMENU_META"] = ""
-- L["ICONMENU_META_DESC"] = ""
-- L["ICONMENU_MOUSEOVER"] = ""
-- L["ICONMENU_MOUSEOVERTARGET"] = ""
-- L["ICONMENU_MULTISTATECD"] = ""
-- L["ICONMENU_MULTISTATECD_DESC"] = ""
-- L["ICONMENU_ONLYINTERRUPTIBLE"] = ""
L["ICONMENU_ONLYMINE"] = "Mostrar sólo si se emiten por sí mismo" -- Needs review
L["ICONMENU_OPTIONS"] = "Más opciones" -- Needs review
L["ICONMENU_PETTARGET"] = "objetivo de mascotas" -- Needs review
L["ICONMENU_PRESENT"] = "Present"
L["ICONMENU_RANGECHECK"] = "Comprobar Gama?" -- Needs review
-- L["ICONMENU_RANGECHECK_DESC"] = ""
L["ICONMENU_REACT"] = "Reacción del Unidad" -- Needs review
L["ICONMENU_REACTIVE"] = "hechizo reactiva o la capacidad" -- Needs review
L["ICONMENU_SETALPHA"] = "Establecer el nivel alfa" -- Needs review
-- L["ICONMENU_SETALPHAMOD"] = ""
L["ICONMENU_SHOWCBAR"] = "Mostrar el tiempo de reutilización / barra de temporizador" -- Needs review
L["ICONMENU_SHOWPBAR"] = "Mostrar barra de poder" -- Needs review
L["ICONMENU_SHOWTIMER"] = "Mostrar reloj" -- Needs review
-- L["ICONMENU_SHOWTIMERTEXT"] = ""
-- L["ICONMENU_SHOWTIMERTEXT_DESC"] = ""
L["ICONMENU_SHOWWHEN"] = "Mostrar icono cuando" -- Needs review
L["ICONMENU_SPELL"] = "hechizo o habilidad" -- Needs review
L["ICONMENU_STACKS_MAX_DESC"] = "Cantidad máxima de las pilas del aura es necesario para mostrar el icono" -- Needs review
L["ICONMENU_STACKS_MIN_DESC"] = "Número mínimo de las pilas del aura es necesario para mostrar el icono" -- Needs review
L["ICONMENU_TARGET_OR_FOCUS"] = "El objectivo o enfoque" -- Needs review
L["ICONMENU_TARGETTARGET"] = "El objectivo del objectivo" -- Needs review
L["ICONMENU_TOTEM"] = "Totem / Ghoul no MoG" -- Needs review
-- L["ICONMENU_TOTEM_DESC"] = ""
L["ICONMENU_TYPE"] = "Icono de tipo" -- Needs review
L["ICONMENU_UNIT"] = "Unidad de ver" -- Needs review
L["ICONMENU_UNUSABLE"] = "Inutilizable"
L["ICONMENU_USABLE"] = "útil"
-- L["ICONMENU_VEHICLE"] = ""
L["ICONMENU_WPNENCHANT"] = "temporal encantar arma" -- Needs review
L["ICONMENU_WPNENCHANTTYPE"] = "ranura de armas para controlar" -- Needs review
-- L["ICONTOCHECK"] = ""
L["ICON_TOOLTIP1"] = "TellMeWhen"
L["ICON_TOOLTIP2"] = "Haga clic en el icono para conocer las opciones más opciones en la interfaz de Blizzard opciones del menú Tipo /tmw para bloquear y permitir complemento..." -- Needs review
-- L["ImmuneToMagicCC"] = ""
-- L["ImmuneToStun"] = ""
-- L["Incapacitated"] = ""
-- L["IncreasedAP"] = ""
-- L["IncreasedCrit"] = ""
-- L["IncreasedDamage"] = ""
-- L["IncreasedPhysHaste"] = ""
-- L["IncreasedSPsix"] = ""
-- L["IncreasedSPten"] = ""
-- L["IncreasedSpellHaste"] = ""
-- L["IncreasedStats"] = ""
-- L["LDB_TOOLTIP1"] = ""
-- L["LDB_TOOLTIP2"] = ""
-- L["MOON"] = ""
-- L["Magic"] = ""
-- L["ManaRegen"] = ""
-- L["NONE"] = ""
-- L["OUTLINE_NO"] = ""
-- L["OUTLINE_THICK"] = ""
-- L["OUTLINE_THIN"] = ""
-- L["PhysicalDmgTaken"] = ""
-- L["Poison"] = ""
-- L["PushbackResistance"] = ""
L["RESIZE"] = "tamaño" -- Needs review
L["RESIZE_TOOLTIP"] = "Haz clic y arrastra para cambiar el tamaño" -- Needs review
-- L["RLWARN"] = ""
-- L["ReducedArmor"] = ""
-- L["ReducedAttackSpeed"] = ""
-- L["ReducedCastingSpeed"] = ""
-- L["ReducedHealing"] = ""
-- L["ReducedPhysicalDone"] = ""
-- L["Resistances"] = ""
-- L["Rooted"] = ""
-- L["STACKSPANEL_TITLE"] = ""
-- L["SUN"] = ""
-- L["Silenced"] = ""
-- L["SpellCritTaken"] = ""
-- L["SpellDamageTaken"] = ""
-- L["Stunned"] = ""
-- L["TO"] = ""
-- L["TRUE"] = ""
L["UIPANEL_ALLRESET"] = "Restablecer todos los iconos" -- Needs review
-- L["UIPANEL_BARIGNOREGCD"] = ""
-- L["UIPANEL_BARIGNOREGCD_DESC"] = ""
L["UIPANEL_BARTEXTURE"] = "Barra de textura" -- Needs review
-- L["UIPANEL_CLOCKIGNOREGCD"] = ""
-- L["UIPANEL_CLOCKIGNOREGCD_DESC"] = ""
L["UIPANEL_COLOR"] = "Tiempo de reutilización / Barras de Color Duración" -- Needs review
-- L["UIPANEL_COLORS"] = ""
-- L["UIPANEL_COLOR_ABSENT"] = ""
-- L["UIPANEL_COLOR_ABSENT_DESC"] = ""
L["UIPANEL_COLOR_COMPLETE"] = "CD / Duración completa" -- Needs review
L["UIPANEL_COLOR_COMPLETE_DESC"] = "color de la barra cuando el tiempo de reutilización / duración es completo" -- Needs review
-- L["UIPANEL_COLOR_DESC"] = ""
L["UIPANEL_COLOR_OOM"] = "De color de poder" -- Needs review
L["UIPANEL_COLOR_OOM_DESC"] = "Matiz y alfa del icono cuando te falta el mana / ira / energía / enfoque / runicpower para lanzar el hechizo" -- Needs review
L["UIPANEL_COLOR_OOR"] = "Fuera de la gama de colores" -- Needs review
L["UIPANEL_COLOR_OOR_DESC"] = "Matiz y alfa del icono cuando no están en el rango de la meta de lanzar el hechizo" -- Needs review
-- L["UIPANEL_COLOR_PRESENT"] = ""
-- L["UIPANEL_COLOR_PRESENT_DESC"] = ""
L["UIPANEL_COLOR_STARTED"] = "CD / Duración de comenzar" -- Needs review
L["UIPANEL_COLOR_STARTED_DESC"] = "color de la barra cuando el tiempo de reutilización / duración ha hecho más que empezar" -- Needs review
L["UIPANEL_COLUMNS"] = "Columnas" -- Needs review
-- L["UIPANEL_CONDENSE"] = ""
L["UIPANEL_DRAWEDGE"] = "Resaltar borde temporizador" -- Needs review
L["UIPANEL_DRAWEDGE_DESC"] = "Destaca el borde del temporizador de tiempo de reutilización (la animación del reloj) para aumentar la visibilidad" -- Needs review
L["UIPANEL_ENABLEGROUP"] = "Habilitar el Grupo" -- Needs review
-- L["UIPANEL_FONT"] = ""
-- L["UIPANEL_FONT_DESC"] = ""
-- L["UIPANEL_FONT_OUTLINE"] = ""
-- L["UIPANEL_FONT_OUTLINE_DESC"] = ""
-- L["UIPANEL_FONT_SIZE"] = ""
-- L["UIPANEL_FONT_SIZE_DESC"] = ""
L["UIPANEL_GROUPRESET"] = "Posición Inicial" -- Needs review
L["UIPANEL_GROUPRESETHEADER"] = "Posición Inicial" -- Needs review
-- L["UIPANEL_GROUPS"] = ""
L["UIPANEL_ICONGROUP"] = "Grupo de Iconos" -- Needs review
-- L["UIPANEL_ICONSPACING"] = ""
-- L["UIPANEL_ICONSPACING_DESC"] = ""
L["UIPANEL_LOCK"] = "AddOn bloqueo" -- Needs review
L["UIPANEL_LOCKUNLOCK"] = "Bloqueo / Desbloqueo AddOn" -- Needs review
-- L["UIPANEL_MAINOPT"] = ""
-- L["UIPANEL_NOCOUNT"] = ""
-- L["UIPANEL_NOCOUNT_DESC"] = ""
-- L["UIPANEL_NOTINVEHICLE"] = ""
-- L["UIPANEL_NUMGROUPS"] = ""
-- L["UIPANEL_NUMGROUPS_DESC"] = ""
L["UIPANEL_ONLYINCOMBAT"] = "Mostrar sólo en combate" -- Needs review
L["UIPANEL_PRIMARYSPEC"] = "Spec primaria" -- Needs review
-- L["UIPANEL_RELOAD"] = ""
L["UIPANEL_ROWS"] = "Filas"
L["UIPANEL_SECONDARYSPEC"] = "Spec Secundaria" -- Needs review
-- L["UIPANEL_SPEC"] = ""
L["UIPANEL_STANCE"] = "Mostrar mientras que en:" -- Needs review
L["UIPANEL_SUBTEXT1"] = "Estas opciones le permiten cambiar el número, disposición y el comportamiento de los iconos de recordatorio." -- Needs review
L["UIPANEL_SUBTEXT2"] = "Iconos de trabajo una vez cerradas Cuando desbloqueado, puede mover o grupos icono de tamaño y haga clic derecho en los iconos individuales para más opciones de configuración También puede escribir '/tellmewhen' o '/tmw' para bloquear o desbloquear." -- Needs review
L["UIPANEL_TOOLTIP_ALLRESET"] = "restablecer los datos y la posición de todos los iconos" -- Needs review
L["UIPANEL_TOOLTIP_COLUMNS"] = "Establecer el número de columnas de iconos en este grupo" -- Needs review
-- L["UIPANEL_TOOLTIP_CONDENSE"] = ""
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "Mostrar y permitir que este grupo de iconos" -- Needs review
L["UIPANEL_TOOLTIP_GROUPRESET"] = "Restablecer la posición de este grupo" -- Needs review
-- L["UIPANEL_TOOLTIP_NOTINVEHICLE"] = ""
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "Comprobar para mostrar sólo este grupo de iconos en combate" -- Needs review
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "Comprobar para mostrar el resultado de este grupo de iconos, mientras que su especificación primaria está activa" -- Needs review
L["UIPANEL_TOOLTIP_ROWS"] = "Establecer el número de filas en el icono de este grupo" -- Needs review
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "Comprobar para mostrar el resultado de este grupo de iconos, mientras que su especificación secundaria está activo" -- Needs review
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "Establece la frecuencia (en segundos) que los iconos son revisados para mostrar / ocultar, alfa, condiciones, etc, no afecta demasiado bares. Cero es tan rápido como sea posible. Los valores más bajos pueden tener un impacto significativo en la tasa de fotogramas de gama baja computadoras " -- Needs review
L["UIPANEL_UNLOCK"] = "Desbloquear AddOn" -- Needs review
L["UIPANEL_UPDATEINTERVAL"] = "Intervalo de actualización" -- Needs review
